//
//  EFAnimatedImageFormat.swift
//  EFQRCode
//
//  Created by EyreFree on 2024/9/5.
//
//  Copyright (c) 2017-2024 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation
#if canImport(MobileCoreServices)
import MobileCoreServices
#else
import CoreServices
#endif
import UniformTypeIdentifiers

/**
 * Supported animated image formats for QR code generation.
 *
 * This enum defines the animated image formats that can be generated by EFQRCode.
 * Each format has different characteristics in terms of file size, quality, and
 * browser/device compatibility.
 *
 * ## Supported Formats
 *
 * - **GIF**: Widely supported, smaller file size, limited color palette
 * - **APNG**: Better quality, larger file size, modern browser support
 *
 * ## Usage
 *
 * ```swift
 * let generator = try EFQRCode.Generator("Hello World")
 * 
 * // Generate animated GIF
 * let gifData = try generator.toGIFData(width: 200)
 * 
 * // Generate animated PNG
 * let apngData = try generator.toAPNGData(width: 200)
 * ```
 *
 * ## Format Comparison
 *
 * | Format | File Size | Quality | Browser Support | Animation Support |
 * |--------|-----------|---------|-----------------|-------------------|
 * | GIF    | Smaller   | Lower   | Excellent       | Limited           |
 * | APNG   | Larger    | Higher  | Good            | Full              |
 */
enum EFAnimatedImageFormat: CaseIterable {
    /**
     * Graphics Interchange Format (GIF).
     *
     * GIF is a widely supported animated image format with the following characteristics:
     * - Limited to 256 colors per frame
     * - Excellent browser and device compatibility
     * - Smaller file sizes compared to APNG
     * - Limited animation capabilities
     *
     * Best for: Web use, email attachments, and situations where file size is critical.
     */
    case gif
    
    /**
     * Animated Portable Network Graphics (APNG).
     *
     * APNG is a modern animated image format with the following characteristics:
     * - Full 24-bit color support
     * - Better image quality than GIF
     * - Larger file sizes compared to GIF
     * - Full animation capabilities
     *
     * Best for: High-quality animations, modern applications, and when quality is priority.
     */
    case apng
    
    /**
     * The Core Foundation string identifier for the image format.
     *
     * This property provides the appropriate UTType identifier for the format,
     * handling both modern (iOS 14.0+) and legacy (pre-iOS 14.0) systems.
     *
     * - Returns: The CFString identifier for the image format.
     */
    var identifier: CFString {
        switch self {
        case .gif:
            if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *) {
                return UTType.gif.identifier as CFString
            } else {
                return kUTTypeGIF
            }
        case .apng:
            if #available(iOS 14.0,macOS 11.0, tvOS 14.0, watchOS 7.0, *) {
                return UTType.png.identifier as CFString
            } else {
                return kUTTypePNG
            }
        }
    }
}
