source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

target 'Dependency' do
  pod 'SnapKit', '5.0.1'
  pod 'EFColorPicker', '5.1.0'
  pod 'EFFoundation', '1.1.2'
end
