# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Update dependences"
  lane :local do
    update_build_number
    build
    upload_to_testflight
  end

  desc "Update build number"
  lane :update_build_number do
    latestBuildNumber = Time.now
    update_info_plist(
      xcodeproj: "Examples/iOS/iOS Example.xcodeproj",
      scheme: "iOS Example",
      block: lambda { |plist|
        plist["CFBundleVersion"] = (latestBuildNumber.to_i).to_s
      }
    )
    update_info_plist(
      xcodeproj: "Examples/iOS/iOS Example.xcodeproj",
      scheme: "watchOS Example",
      block: lambda { |plist|
        plist["CFBundleVersion"] = (latestBuildNumber.to_i).to_s
      }
    )
    update_info_plist(
      xcodeproj: "Examples/iOS/iOS Example.xcodeproj",
      scheme: "watchOS Example Extension",
      block: lambda { |plist|
        plist["CFBundleVersion"] = (latestBuildNumber.to_i).to_s
      }
    )
  end

  desc "Make a new build"
  lane :build do
    build_app(project: "Examples/iOS/iOS Example.xcodeproj", scheme: "iOS Example")
  end

  desc "Upload to testflight alpha and beta test"
  lane :upload_testflight do
    upload_to_testflight(
      beta_app_review_info: {
        contact_email: "eyrefree@eyrefree.org",
        contact_first_name: "Eyre",
        contact_last_name: "Free",
        contact_phone: "+86 17172125161",
        demo_account_name: "",
        demo_account_password: "",
        notes: "EFQRCode's iOS App update, thanks for reviewing."
      },
      localized_build_info: {
        "default": {
          whats_new: "EFQRCode's iOS App update.",
        },
        "en-GB": {
          whats_new: "EFQRCode's iOS App update.",
        },
        "en-US": {
          whats_new: "EFQRCode's iOS App update.",
        }
      },
      skip_waiting_for_build_processing: false, # true 就不自动提审了
      reject_build_waiting_for_review: true, # 取消当前正在审核的 build
      skip_submission: false,
      username: "eyrefree@eyrefree.org",
      app_identifier: "AppStore.EFQRCode",
      beta_app_feedback_email:"eyrefree@eyrefree.org",
      beta_app_description: "EFQRCode's iOS App.",
      demo_account_required: false,
      distribute_external: true, # 构建是否应该分发给外部测试人员？
      notify_external_testers: true,
      groups: "Beta",
      changelog: "EFQRCode's iOS App update",
      beta_app_feedback_email: "eyrefree@eyrefree.org",
      ipa: "EFQRCode.iOS.ipa",
      apple_id: "1242337058",
      team_id: "118360553",
      itc_provider: "P3X2725LYY"
    )
  end
end
