name: Documentation

on:
  push:
    branches:
      - main
      - docs

jobs:
  jazzy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Jazzy
        run: sudo gem install jazzy
      - name: Resolve Swift Package dependencies
        run: xcodebuild -resolvePackageDependencies
      - name: Generate Documentation
        run: ./docs.sh || {
          # 若失败，打印 xcodebuild 日志
          cat /var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/xcodebuild-*.log
          exit 1
        }
        continue-on-error: false
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
